In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../Veriler/08-seismic_activity_svm.csv")
df.head()

   underground_wave_energy  vibration_axis_variation  seismic_event_detected
0                 9.539392                 -3.000000                       0
1                 9.558241                 -2.939394                       0
2                 9.576669                 -2.878788                       0
3                 9.594678                 -2.818182                       0
4                 9.612272                 -2.757576                       0

In [3]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   underground_wave_energy   400 non-null    float64
 1   vibration_axis_variation  400 non-null    float64
 2   seismic_event_detected    400 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 9.5 KB
None
       underground_wave_energy  vibration_axis_variation  \
count               400.000000              4.000000e+02
mean                  0.000000              8.881784e-18
std                   7.719350              1.751650e+00
min                  -9.999954             -3.000000e+00
25%                  -6.134779             -1.500000e+00
50%                   0.000000              0.000000e+00
75%                   6.134779              1.500000e+00
max                   9.999954              3.000000e+00

       seismic_event_detected
count              400.000000
mean                 0.500000
std                  0.500626
min                  0.000000
25%                  0.000000
50%                  0.500000
75%                  1.000000
max                  1.000000

In [8]:
x = torch.tensor(df[['underground_wave_energy','vibration_axis_variation']])

     underground_wave_energy  vibration_axis_variation
0                   9.539392                 -3.000000
1                   9.558241                 -2.939394
2                   9.576669                 -2.878788
3                   9.594678                 -2.818182
4                   9.612272                 -2.757576
..                       ...                       ...
395                -4.170824                 -2.757576
396                -4.130115                 -2.818182
397                -4.088102                 -2.878788
398                -4.044745                 -2.939394
399                -4.000000                 -3.000000

[400 rows x 2 columns]